# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=200)),
                ('offer_address', models.TextField()),
                ('offer_date', models.DateTimeField()),
                ('offer_radius', models.IntegerField()),
                ('offer_rate', models.FloatField()),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
