# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20161119_1252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
